
export const ENGLocalizedStrings = {
  Public: {
    All: "All",
    Confirm: "Confirm",
    Cancel: "Cancel",
    Back: "Back",
    Save: "Save",
    Close: "Close",
    Language: "Language: English",
    Post: "Post",
    Friend: "Friend",
    Username: "Username",
    About: "About",
    Today: "Today, what do you want to do?",
    Detail: "Detail",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    LogOut: "Log Out",
    SetingProfile: "Setting Profile",
    Mail: "Email",
    Phone: "Phone Number",
    Birthday: "Birth Date",
    Active: "Created Date",
    FriendFind: "Find Friend",
    FriendView: "View All Friend",
    Conform: "Confirm",
    LogoutConfirm: "Are you sure you want to log out?",
    More: "More",
    AddFriend: "Add Friend",
    UnFriend: "Unfriend",
    CancelFriendRequest: "Cancel request",
    RefuseFriendRequest: "Refuse",
    AcceptFriendRequest: "Accept",
    ReportFriend: "Report",
    Block: "Block",
    Vietnamese: "Vietnamese",
    English: "English",
    ErrorFetchingProfile: "Error fetching profile!",
    Biography: "Biography",
    UnknownUser: "YourVibes user",
    Public: "Public",
    Everyone: "Everyone",
    Private: "Only me",
    MinuteAgo: "minutes ago",
    HourAgo: "hours ago",
    DayAgo: "days ago",
    Action: "Action",
    CommonActions: "Click your comment ...",
    Comment: "Comments",
    Reply: "Reply",
    ReportComment: "Report Comment",
    Day: "Day",
    HideInfo: "has hidden personal information",
    FriendOnly: "only friends can see",
    UserLikePost: " List of users liked post",
    NoUserLikePost: "No one liked this post",
  },
  Form: {
    Label: {
      Email: "Email",
      Password: "Password",
      FamilyName: "Family Name",
      Name: "Name",
      Phone: "Phone Number",
      BirthDay: "Birth Date",
      GetOTP: "Enter OTP",
      OTP: "OTP Code",
      ConfirmPassword: "Confirm Password",
      Biography: "Biography",
    },
    RequiredMessages: {
      FamilyNameRequiredMessage: "Please enter family name!",
      NameRequiredMessage: "Please enter name!",
      PhoneRequiredMessage: "Please enter phone number!",
      BirthDayRequiredMessage: "Please select a birth date!",
      EmailRequiredMessage: "Please enter email!",
      PasswordRequiredMessage: "Please enter password!",
      ConfirmPasswordRequiredMessage: "Please confirm your password!",
      AgreeRequiredMessage: "Please agree to the terms!",
      OTPRequiredMessage: "Please enter OTP code!",
      OTPPressRequiredMessage: "Please receive OTP code!",
    },
    TypeMessage: {
      EmailTypeMessage: "Invalid email!",
      PasswordTypeMessage: "Password must be over 8 characters!",
      ConfirmPasswordTypeMessage: "Confirm password is invalid!",
      OTPTypeMessage: "OTP code must be a 6-digit string!",
      PhoneTypeMessage: "Phone number must be a 10-digit string!",
    },
  },
  Login: {
    LoginButton: "Login",
    ForgotPasswordText: "Forgot password?",
    DontHaveAccout: "Don't have an account?",
    SignUpNow: "Sign up now!",
    Or: "Or",
    LoginFailed: "Login failed!",
  },
  SignUp: {
    SignUpButton: "Sign up",
    SignUpSuccess: "Sign up successful! Please log in again",
    SignUpFailed: "Sign up failed!",
    OTPSuccess: "OTP has been sent successfully!",
    OTPAlreadySent: "OTP has been sent and is valid for 10 minutes!",
    OTPFailed: "Sending OTP failed!",
    AlreadyHaveAccount: "Already have an account?",
    LoginNow: "Log in now!",
    AgreePolicies: "I agree to the YourVibes terms",
  },
  AddPost: {
    NewPost: "New post",
    WhatDoYouThink: "What do you think?",
    PrivacyText: "Share your post with",
    PostNow: "Post now",
    CreatePostSuccess: "Create post successful!",
    CreatePostFailed: "Create post failed!",
    EmptyContent: "Missing content or media file",
    PickImgFailed: "Pick images failed!",
  },
  ObjectPostPrivacy: {
    PublicDescription: "Everyone on YourVibes",
    FriendDescription: "Only friends on YourVibes",
    PrivateDescription: "Only you can see the post",
    PostPrivacy: "Post's privacy",
    Contents: {
      WhoCanSee: "Who can see your post?",
      CanFind: "Your post may appear on your profile and in search results.",
      DefaultPrivacy1: "Although the default audience is ",
      DefaultPrivacy2: ", you can change the audience for this specific post.",
    },
    ChoosePrivacy: "Choose Privacy",
  },
  ObjectProfile: {
    ProfilePrivacy: "Profile's privacy",
    Contents: {
      WhoCanSee: "Who can see your information?",
      DefaultPrivacy2: ", but you can change the privacy for your account details.",
    },
  },
  Post: {
    EditPost: "Edit post",
    EditPrivacy: "Edit post's privacy",
    DeletePost: "Delete post",
    Advertisement: "Advertisement",
    ReportPost: "Report post",
    LikePostFailed: "Like post failed!",
    SharePostSuccess: "Share post successful!",
    SharePostFailed: "Share post failed!",
    SharePost: "Share",
    DeleteNewFeed: "Delete (hide) new feed",
    NoContent: "Content is empty",
    Sponsor: "Sponsored",
  },
  PostDetails:{
    ViewReplies: "View replies",
    HideReplies:"Hide replies",
    Save: "Save",
    Cancel: "Cancel",
    Error: "Error",
    ErrorReplies: "Failed to get replies!",
    ReportComment: "Report comment",
    EditComment: "Edit comment",
    DeleteComment: "Delete comment",
    ActionOptions:"Action options",
    ReportSusesfully: "Reported succeeded!",
    Success: "Success",
    EditCommentSuccess: "Edit comment successful!",
    EditCommentFailed: "Edit comment failed!",
    EditReplySuccess: "Edit reply successful!",
    EditReplyFailed: "Edit reply failed!",
    DeteleReplyFailed: "Delete reply failed!",
    DeteleReplySuccess: "Delete reply successful!",
    CommentSuccess: "Comment successful!",
    CommentFailed: "Comment failed!",
    ReplySuccess: "Reply successful!",
    ReplyFailed: "Reply failed!",
    Yes: "Yes",
    No: "No",
    CommentNotFound: "Comment not found!",
  },
  Profile: {
    Posts: {
      GetPostsFailed: "Failed to get posts!",
      GetOnePostFailed: "Failed to get post!",
    },
    Info: {
      GetInfoFailed: "Failed to get user's infomation!",
    },
    Friend: {
      SendYouARequest: "Sent you a friend request!",
      SendARequest: "Sent friend request!",
      SendRequestFailed: "Failed to send friend request!",
      SendRequestSuccess: "Friend request sent successfully!",
      FriendResponseFailed: "Failed to respond to friend request!",
      FriendResponseSuccess: "Friend request response successful!",
      CancelRequestFailed: "Failed to cancel friend request!",
      CancelRequestSuccess: "Friend request canceled successfully!",
      UnfriendFailed: "Failed to unfriend!",
      UnfriendSuccess: "Unfriend successful!",
      UnfriendConfirm: "Are you sure you want to unfriend this user?",
    },
  },
  UpdatePost: {
    UpdatePostSuccess: "Update post successful!",
    UpdatePostFailed: "Update post failed!",
  },
  DeletePost: {
    DeleteConfirm: "Are you sure you want to delete this post?",
    DeleteSuccess: "Delete post successful!",
    DeleteFailed: "Delete post failed!",
  },
  UpdateProfile: {
    UpdateProfile: "Update profile",
    UpdateFailed: "Update profile failed!",
    UpdateSuccess: "Update profile successful!",
  },
  Search: {
    Search: "Search",
    SearchPlaceholder: "Searching...",
    SearchFailed: "Search failed!",
    NoUsers: "No user found",
    TrySearch: "Try searching some keyword",
  },
  Notification: {
    Notification: "Notification",
    Items: {
      LikePost: "liked your post: ",
      SharePost: "shared your post: ",
      CommentPost: "commented on your post: ",
      Friend: "sent you a friend request.",
      AcceptFriend: "accepted your friend request.",
    NewPost: "posted a new post.",
    LikeComment: "liked your comment: ",
    },
  },
  ListFriends: {
    ListFriends: "List friends",
    Search: "Search . . .",
    ViewProfile: "View profile",
    Unfriend: "Unfriend ",
    Block: "Block ",
    Cancel: "Cancel",
  },

  Ads: {
    Ads: "Post Advertisement",
    TimeAndBudget: "Duration and Budget",
    Minimum: "Minimum: {{price}}/day (Max date: 30 days)",
    DaysAds: "Number of advertisement days:",
    TimeAds: "Advertisement duration: ",
    StartDate: "Start Date",
    EndDate: "End Date",
    BudgetAds: "Budget: ",
    PaymentMethod: "Payment method",
    AdvertisePostFailed: "Advertise post failed!",
    AdvertisePostSuccess: "Advertise post successful!",
    ActiveCampaign: "Active campaign",
    HideCampaign:"Hide campaign",
    ShowCampaign:"Show campaign",
    Campaign: "Campaign",
    End:"End",
    RemainingTime:"Remaining time",
    Day:"Day",
    Grant:"Grant", 
    Status:"Status",
    PaymentSuccess: "Payment successful.",
    PaymentFailed: "Payment failed.",
    NoCampaign: "No campaign found",
  },

  Report: {
    ReportPost: "Why are you reporting this post?",
    ReportUser: "Why are you reporting this user?",
    ReportComment: "Why are you reporting this comment?",
    ReportSuccess: "Reported successfully!",
    ReportFailed: "Report failed!",
    Note: "If you see a threat or someone in danger, don't hesitate to seek help and report to local emergency services before reporting to YourVibes.",
    placeholder:"Write your report here..."
  },
  ChangePassword: {
    ChangePassword: "Change password",
    ChangePasswordFailed: "Change password failed!",
    ChangePasswordSuccess: "Change password successful!",
    OldPassword: "Old password",
    NewPassword: "New password",
    ConformPassword: "Confirm password",
    Email: "Email",
    SendOTP: "Send OTP",
    OTP: "OTP",
    ConformChangePassword: "Confirm change password",
  },
}
