export const VnLocalizedStrings = {
  Public: {
    All: "Tất cả",
    Confirm: "Xác nhận",
    Cancel: "Hủy",
    Back: "Quay lại",
    Save: "Lưu",
    Close: "Đóng",
    Language: "Ngôn ngữ: Tiếng Việt",
    Post: "Bài Viết",
    Friend: "Bạn Bè",
    Username: "Tên người dùng",
    About: "Giới Thiệu",
    Today: "Hôm nay bạn thế nào?",
    Detail: "Chi tiết",
    EditProfile: "Chỉnh sửa trang cá nhân",
    ChangePassword: "Thay đổi mật khẩu",
    LogOut: "Đăng xuất",
    SetingProfile: "Cài đặt trang cá nhân",
    Mail: "Email",
    Phone: "Số điện thoại",
    Birthday: "Ngày sinh",
    Active: "Ngày tham gia",
    FriendFind: "Tìm bạn bè",
    FriendView: "Xem tất cả bạn bè",
    Conform: "Xác nhận",
    LogoutConfirm: "Bạn có chắc chắn muốn đăng xuất",
    More: "Xem thêm",
    AddFriend: "Kết bạn",
    UnFriend: "Hủy kết bạn",
    CancelFriendRequest: "Hủy lời mời",
    RefuseFriendRequest: "Từ chối",
    AcceptFriendRequest: "Chấp nhận",
    ReportFriend: "Báo Cáo",
    Block: "Chặn",
    Vietnamese: "Tiếng Việt",
    English: "Tiếng Anh",
    ErrorFetchingProfile: "Lỗi hiển thị thông tin",
    Biography: "Giới thiệu",
    UnknownUser: "Người dùng YourVibes",
    Public: "Công khai",
    Everyone: "Mọi người",
    Private: "Chỉ mình tôi",
    MinuteAgo: "phút trước",
    HourAgo: "giờ trước",
    DayAgo: "ngày trước",
    Action: "Hành động",
    CommonActions: "Nhập bình luận của bạn ...",
    Comment: "Bình luận",
    Reply: "Trả lời",
    ReportComment: "Báo cáo bình luận",
    Day: "Ngày",
  },
  Form: {
    Label: {
      Email: "Email",
      Password: "Mật khẩu",
      FamilyName: "Họ",
      Name: "Tên",
      Phone: "Số điện thoại",
      BirthDay: "Ngày sinh",
      GetOTP: "Nhập OTP",
      OTP: "Mã OTP",
      ConfirmPassword: "Xác nhận mật khẩu",
      Biography: "Tiểu sử",
    },
    RequiredMessages: {
      FamilyNameRequiredMessage: "Vui lòng nhập họ!",
      NameRequiredMessage: "Vui lòng nhập tên!",
      PhoneRequiredMessage: "Vui lòng nhập số điện thoại!",
      BirthDayRequiredMessage: "Vui lòng chọn ngày sinh!",
      EmailRequiredMessage: "Vui lòng nhập email!",
      PasswordRequiredMessage: "Vui lòng nhập mật khẩu!",
      ConfirmPasswordRequiredMessage: "Vui lòng xác nhận mật khẩu!",
      AgreeRequiredMessage: "Vui lòng đồng ý các điều khoản!",
      OTPRequiredMessage: "Vui lòng nhập mã OTP!",
      OTPPressRequiredMessage: "Vui lòng nhận mã OTP!",
    },
    TypeMessage: {
      EmailTypeMessage: "Email không hợp lệ!",
      PasswordTypeMessage: "Mật khẩu phải trên 8 kí tự!",
      ConfirmPasswordTypeMessage: "Xác nhận mật khẩu không hợp lệ!",
      OTPTypeMessage: "Mã OTP phải là chuỗi 6 số!",
      PhoneTypeMessage: "Số điện thoại phải là chuỗi 10 số!",
    },
  },

  Login: {
    LoginButton: "Đăng nhập",
    ForgotPasswordText: "Quên mật khẩu?",
    DontHaveAccout: "Bạn chưa có tài khoản?",
    SignUpNow: "Đăng ký ngay!",
    Or: "Hoặc",
    LoginFailed: "Đăng nhập thất bại!",
  },

  SignUp: {
    SignUpButton: "Đăng ký",
    SignUpSuccess: "Đăng ký thành công! Vui lòng đăng nhập lại",
    SignUpFailed: "Đăng ký thất bại!",
    OTPSuccess: "OTP đã được gửi thành công!",
    OTPAlreadySent: "Mã OTP đã được gửi và tồn tại trong 10 phút!",
    OTPFailed: "Gửi OTP thất bại!",
    AlreadyHaveAccount: "Bạn đã có tài khoản?",
    LoginNow: "Đăng nhập ngay!",
    AgreePolicies: "Tôi đồng ý các điều khoản của YourVibes",
  },
  AddPost: {
    NewPost: "Bài đăng mới",
    WhatDoYouThink: "Bạn đang nghĩ gì?",
    PrivacyText: "Bài đăng được chia sẻ với",
    PostNow: "Đăng ngay",
    CreatePostSuccess: "Đăng bài thành công!",
    CreatePostFailed: "Đăng bài thất bại!",
    EmptyContent: "Thiếu nội dung hoặc file media",
    PickImgFailed: "Tải file thất bại!",
  },
  ObjectPostPrivacy: {
    PublicDescription: "Bất kỳ ai ở trên YourVibes",
    FriendDescription: "Chỉ bạn bè của bạn ở trên YourVibes",
    PrivateDescription: "Chỉ bạn có thể nhìn thấy",
    PostPrivacy: "Đối tượng của bài viết",
    Contents: {
      WhoCanSee: "Ai có thể nhìn thấy bài viết của bạn?",
      CanFind:
        "Bài viết của bạn có thể hiện thị trên trang cá nhân và trong kết quả tìm kiếm.",
      DefaultPrivacy1: "Tuy đối tượng mặc định là ",
      DefaultPrivacy2:
        ", nhưng bạn có thể thay đổi đối tượng của riêng bài viết này.",
    },
    ChoosePrivacy: "Chọn Đối tượng",
  },
  Post: {
    EditPost: "Chỉnh sửa bài đăng",
    EditPrivacy: "Chỉnh sửa quyền riêng tư",
    DeletePost: "Xóa bài đăng",
    Advertisement: "Quảng cáo bài đăng",
    ReportPost: "Báo cáo bài đăng",
    LikePostFailed: "Thích bài viết thất bại!",
    SharePostSuccess: "Chia sẻ bài viết thành công!",
    SharePostFailed: "Chia sẻ bài viết thất bại!",
    SharePost: "Chia sẻ",
    DeleteNewFeed: "Ẩn bài viết",
    NoContent: "Nội dung không hiển thị",
    Sponsor: "Được tài trợ",
  },
  PostDetails:{
    ViewReplies: "Xem phản hồi",
    HideReplies:"Ẩn phản hồi",
    Save:"Lưu",
    Cancel:"Hủy",
    Error: "Lỗi",
    ErrorReplies: "Lỗi phản hồi",
    ReportComment: "Báo cáo bình luận",
    EditComment: "Chỉnh sửa bình luận",
    DeleteComment: "Xóa bình luận",
    ActionOptions:"Chọn hành động",
    ReportSusesfully:"Báo cáo bình luận thành cônng!",
    Success  :"Thành công",
    EditCommentSuccess: "Cập nhật bình luận thành công!",
    EditCommentFailed: "Cập nhật bình luận thát bị!",
    EditReplySuccess: "Cập nhật phân hồi thành công!",
    EditReplyFailed: "Cập nhật phân hồi thát bại!",
    DeteleReplyFailed: "Xóa phân hồi thát bại!",
    DeteleReplySuccess: "Xóa phân hồi này này!",
    CommentSuccess: "Bình luận thành công!",
    CommentFailed: "Bình luận thát bại!",
    ReplySuccess: "Phân hồi thành công!",
    ReplyFailed: "Phân hồi thát bại!",
    Yes:"Xác nhận",
    No:"Không",
    CommentNotFound: "Không tìm thấy bình luận!",
  },
  Profile: {
    Posts: {
      GetPostsFailed: "Lấy danh sách bài viết thất bại!",
      GetOnePostFailed: "Lấy bài viết thất bại!",
    },
    Info: {
      GetInfoFailed: "Lấy thống tin người dùng thất bại!",
    },
    Friend: {
      SendYouARequest: "Đã gửi cho bạn một lời mời kết bạn!",
      SendARequest: "Đã gửi lời mời kết bạn!",
      SendRequestFailed: "Gửi lời mời kết bạn thất bại!",
      SendRequestSuccess: "Gửi lời mời kết bạn thành công!",
      FriendResponseFailed: "Phản hồi lời mời thất bại!",
      FriendResponseSuccess: "Phản hồi lời mời thành công!",
      CancelRequestFailed: "Hủy lời mời thất bại!",
      CancelRequestSuccess: "Hủy lời mời thành công!",
      UnfriendFailed: "Hủy kết bạn thất bại!",
      UnfriendSuccess: "Hủy kết bạn thành công!",
      UnfriendConfirm: "Bạn có muốn hủy kết bạn với người dùng này?",
    },
  },
  UpdatePost: {
    UpdatePostSuccess: "Cập nhật bài đăng thành công!",
    UpdatePostFailed: "Cập nhật bài đăng thất bại!",
  },
  DeletePost: {
    DeleteConfirm: "Bạn chắc chắn muốn xóa bài viết này?",
    DeleteSuccess: "Xóa bài viết thành công!",
    DeleteFailed: "Xóa bài viết thát bại!",
  },
  UpdateProfile: {
    UpdateProfile: "Cập nhật trang cá nhân",
    UpdateFailed: "Cập nhật trang cá nhân thất bại!",
    UpdateSuccess: "Cập nhật trang cá nhân thành công!",
  },
  Search: {
    Search: "Tim kiếm",
    SearchPlaceholder: "Bạn đang tìm gì...",
    SearchFailed: "Tìm kiếm thất bại!",
    NoUsers: "Không tìm thấy người dùng",
    TrySearch: "Hãy nhập từ khóa cần tìm",
  },
Notification: {
  Notification: "Thông báo",
  Items:{
    LikePost: "đã thích bài viết của bạn: ",
    SharePost: "đã chia sẻ bài viết của bạn: ",
    CommentPost: "đã bình luận về bài viết của bạn: ",
    Friend: "đã gưi lời mời kết bạn.",
    AcceptFriend: "đã chấp nhận lời mời kết bạn của bạn.",
    NewPost: "đã đăng một bài viết mới.",
    LikeComment: "đã thích bình luận của bạn: ",
    }
  }, 
ListFriends: {
  ListFriends: "Danh sách bạn bè",
  Search: "Tim kiếm . . .",
  ViewProfile: "Xem trang cá nhân",
  Unfriend: "Hủy kết bạn ",
  Block: "Chặn ",
  Cancel: "Hủy",
},

Ads: {
  Ads: "Quảng cáo bài viết",
  TimeAndBudget: "Khoảng thời gian và Ngân sách",
  Minimum: "Tối thiểu: {{price}}/1 ngày (Tối đa: 30 ngày)",
  DaysAds: "Số ngày quảng cáo:",
  TimeAds: "Thời gian quảng cáo: ",
  BudgetAds: "Ngân sách: ",
  PaymentMethod: "Phương thức thanh toán",
  AdvertisePostFailed: "Quảng cáo bài viết thất bại!",
  AdvertisePostSuccess: "Quảng cáo bài viết thành công!",
  ActiveCampaign: "Chiến dịch đang thực hiện",
  HideCampaign:"Ẩn lịch sử",
  ShowCampaign:"Xem lịch sử",
  Campaign:"Chiến dịch",
  End: "Kết thúc",
  RemainingTime:"Thời gian còn lại",
  Day:"Ngày",
  Grant:"Kinh phí", 
  Status:"Trạng thái",
  PaymentSuccess:"Thanh toán thành công", 
  PaymentFailed:"Thanh toán thất bại",
  NoCampaign:"Không có chiến dịch nào",
},


Report: {
  ReportPost: " Tại sao bạn báo cáo bài viết này?",
  ReportUser: "Tại sao bạn báo cáo người dùng này?",
  ReportComment:"Tại sao bạn báo cáo bình luận này?",
  ReportSuccess: "Báo cáo thành công!",
  ReportFailed: "Báo cáo thất bại!",
  Note: "Nếu bạn nhận thấy sự đe dọa hoặc ai đó dang gặp nguy hiểm, đừng chần chừ mà hãy tìm ngay sự giúp đỡ và báo cho dịch vụ khẩn cấp ở địa phương trước khi báo cáo với YourVibes.",
},
ChangePassword:{
  ChangePassword: "Thay đổi mật khẩu",
  ChangePasswordFailed: "Thay đổi mật khẩu thất bại!",
  ChangePasswordSuccess: "Thay đổi mật khẩu thành công!",
  OldPassword: "Mật khẩu cũ",
  NewPassword: "Mật khẩu mới",
  ConformPassword: "Xác nhận mật khẩu mới",
  Email: "Email",
  SendOTP: "Nhận OTP",
  OTP: "Mã OTP",
  ConformChangePassword: "Xác nhận thay đổi mật khẩu",
},
ForgotPassword: {
  ForgotPassword: "Quên mật khẩu",
  Phone: "Số điện thoại",
  Email: "Email",
  SendOTP: "Enter OTP",
  OTP: "Mã OTP",
  NewPassword: "Mật khẩu mới",
  ConfirmPassword: "Xác nhận mật khẩu",
  ConformChangePassword: "Xác nhận cập nhật mật khẩu",
  AlreadyAccount:"Bạn đã nhớ tài khoản?",
}
}